/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_XGBOOST_U_H
#define EDGER8R_XGBOOST_U_H

#include <openenclave/host.h>

#include "xgboost_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_xgboost_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const void* config,
    uint32_t config_size,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t enclave_helloworld(oe_enclave_t* enclave);

oe_result_t enclave_XGDMatrixCreateFromFile(
    oe_enclave_t* enclave,
    int* _retval,
    const char* fname,
    int silent,
    DMatrixHandle* out);

oe_result_t enclave_XGBoosterCreate(
    oe_enclave_t* enclave,
    int* _retval,
    const DMatrixHandle* dmats,
    bst_ulong len,
    BoosterHandle* out);

oe_result_t enclave_XGBoosterSetParam(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    const char* name,
    const char* value);

oe_result_t enclave_XGBoosterUpdateOneIter(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    int iter,
    DMatrixHandle dtrain);

oe_result_t enclave_XGBoosterEvalOneIter(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    int iter,
    DMatrixHandle* dmats,
    const char** evnames,
    bst_ulong len,
    const char** out_str);

/**** OCALL prototypes. ****/
void host_helloworld(void);

int host_rabit__GetRank(void);

int host_rabit__GetWorldSize(void);

int host_rabit__IsDistributed(void);

DIR* host_opendir(char* path);

void* host_opendir_and_readdir(char* path);

struct stat host_stat(char* path);

FILE* host_fopen(
    char* fname,
    char* flag);

void host_fclose(FILE* fp);

FILE* host_fseek(
    FILE* fp,
    long int pos);

void* host_fread_one(
    FILE* fp,
    size_t size);

OE_EXTERNC_END

#endif // EDGER8R_XGBOOST_U_H
