/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_XGBOOST_U_H
#define EDGER8R_XGBOOST_U_H

#include <openenclave/host.h>

#include "xgboost_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_xgboost_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** ECALL prototypes. ****/
oe_result_t enclave_helloworld(oe_enclave_t* enclave);

oe_result_t enclave_XGDMatrixCreateFromFile(
    oe_enclave_t* enclave,
    int* _retval,
    const char* fname,
    int silent,
    DMatrixHandle* out);

oe_result_t enclave_XGBoosterCreate(
    oe_enclave_t* enclave,
    int* _retval,
    const DMatrixHandle* dmats,
    bst_ulong len,
    BoosterHandle* out);

oe_result_t enclave_XGBoosterSetParam(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    const char* name,
    const char* value);

oe_result_t enclave_XGBoosterUpdateOneIter(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    int iter,
    DMatrixHandle dtrain);

oe_result_t enclave_XGBoosterEvalOneIter(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    int iter,
    DMatrixHandle* dmats,
    const char** evnames,
    bst_ulong len,
    const char** out_str);

oe_result_t enclave_XGBoosterPredict(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    DMatrixHandle dmat,
    int option_mask,
    unsigned int ntree_limit,
    bst_ulong* out_len,
    const bst_float** out_result);

oe_result_t enclave_XGDMatrixGetFloatInfo(
    oe_enclave_t* enclave,
    int* _retval,
    DMatrixHandle handle,
    const char* field,
    bst_ulong* out_len,
    const bst_float** out_dptr);

oe_result_t enclave_XGBoosterLoadModel(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    const char* fname);

oe_result_t enclave_XGBoosterSaveModel(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle,
    const char* fname);

oe_result_t enclave_XGDMatrixFree(
    oe_enclave_t* enclave,
    int* _retval,
    DMatrixHandle handle);

oe_result_t enclave_XGBoosterFree(
    oe_enclave_t* enclave,
    int* _retval,
    BoosterHandle handle);

/**** OCALL prototypes. ****/
void host_helloworld(void);

int host_rabit__GetRank(void);

int host_rabit__GetWorldSize(void);

int host_rabit__IsDistributed(void);

DIR* host_opendir(char* path);

void* host_opendir_and_readdir(char* path);

struct stat host_stat(char* path);

FILE* host_fopen(
    char* fname,
    char* flag);

void host_fclose(FILE* fp);

FILE* host_fseek(
    FILE* fp,
    long int pos);

void* host_fread_one(
    FILE* fp,
    size_t size);

void host_fwrite_one(
    void* ptr,
    size_t count,
    FILE* fp);

OE_EXTERNC_END

#endif // EDGER8R_XGBOOST_U_H
